### PR TITLE
Move ReadMe.txt to root folder so it's readable on the GitHub repo page

### PR DESCRIPTION
**Pull request by lroathe**
Also, would love to know what you are using this for... did not think OpenPlay was still of interest to anyone :)

Anyway, thanks for the work and moving it to GitHub, appreciated.

### CODE REVIEW

**Comment by keithmalkin** [comment]
Hey Lane, thanks for reaching out to me.  It's such a pleasure to make your acquaintance.  I've seen the work you and several others contributed to OpenPlay over the years, and I was always so impressed.  I was interested in contributing at the same time, but I was always so busy with my app (a game called Battle for the Universe which is available on my website, www.mistysoftware.com) and work and life, that I never got to contributing.

Well, I'm still working on my game.  I'm currently working on porting it to Apple Silicon.  It's an ungodly amount of work to do that.  One of the hurdles is, of course, OpenPlay.  So I took a quick look to see what it would take to get OpenPlay on Apple Silicon.  I was happy to see that it actually wasn't that much work to port 95% of it.  I was able to hack it up in just a day or two.

After seeing how feasible the port was, I decided to do it right by paying attention to some details and putting the source on GitHub.  (GitHub has been a learning experience for me, as the last source code control system I used was CVS many moons ago.)

Would you like for me to give you direct access to the repository?  I would be happy to do so.  Do you have any time these days?  I would enjoy hearing what you are working on.

Regarding the Read Me, I was thinking of doing a new Read Me and leaving the old one where it is for historical purposes.  What do you think?

Again, so glad to make your acquaintance.  I have so much respect for you and the others that contributed to OpenPlay over the years.  I am a huge fan of OpenPlay.

**Comment by mistysoftware** [comment]
Lane, are you there?j

**Comment by keithmalkin** [comment]
Lane, are you there?

**Comment by lroathe** [comment]
Apologies for the delay in responding, have been busy this morning :)


> On Sep 11, 2021, at 12:52 AM, keithmalkin ***@***.***> wrote:
> 
> 
> Hey Lane, thanks for reaching out to me. It's such a pleasure to make your acquaintance.

Great to make your acquaintance as well.

> I've seen the work you and several others contributed to OpenPlay over the years, and I was always so impressed. I was interested in contributing at the same time, but I was always so busy with my app (a game called Battle for the Universe which is available on my website, www.mistysoftware.com) and work and life, that I never got to contributing.

I know how the time considerations go, never seems to be enough to do everything you’d like to.

> Well, I'm still working on my game. I'm currently working on porting it to Apple Silicon. It's an ungodly amount of work to do that. One of the hurdles is, of course, OpenPlay. So I took a quick look to see what it would take to get OpenPlay on Apple Silicon. I was happy to see that it actually wasn't that much work to port 95% of it. I was able to hack it up in just a day or two.

That is awesome! I must say, it was unexpected to see a message saying there had been a recent update to OpenPlay :)

> After seeing how feasible the port was, I decided to do it right by paying attention to some details and putting the source on GitHub. (GitHub has been a learning experience for me, as the last source code control system I used was CVS many moons ago.)

Hint; don’t try to get fancy with git, keep it simple and it’s pretty decent. Bad things can happen if you start trying to use the advanced features without really understanding them. From experience ;p

> Would you like for me to give you direct access to the repository? I would be happy to do so.

No need, I’ve already forked it and made my first pull request. I can walk you through that if you’d like. This structure is how git wants to work, it can get messy if you don’t follow that (git basically wants all developers using their own repos, using a ’tree’ structure of pull requests).

I have another pull request ready once the current is merged that addresses some fairly serious and not-so serious issues identified by the clang static code analysis.

> Do you have any time these days?

Very little, but I just happened to be unable to sleep last night, so good timing :)

> I would enjoy hearing what you are working on.

I am doing a bunch of Apple II projects in my spare time. See http://www.ideasfromthedeep.com for two big ones.

Professionally, I work on the Mac team at Quicken, inc. on their desktop personal finance application. It’s a great team and the product continues to get better.

> Regarding the Read Me, I was thinking of doing a new Read Me and leaving the old one where it is for historical purposes. What do you think?

That would work. In that case, you can reject and close my pull request with that note. This is one of the good things about the git structure, you don’t have to revert my changes, just not accept them when you have a better solution.

> Again, so glad to make your acquaintance. I have so much respect for you and the others that contributed to OpenPlay over the years. I am huge fan of OpenPlay.

Heh, that’s great to hear. It’s amazing it’s still being used after all these years. I look forward to checking out Battle for the Universe once it runs on OS X 12+.

Later,

-Lane

PS: as implied above, my time is often limited, it may take several days before I am able to respond. If it goes over a week, feel free to ping me.

**Comment by lroathe** [comment]
Closing in favor of a new, improved, readme and leaving this old one where it is.

**Comment by keithmalkin** [comment]
> Apologies for the delay in responding, have been busy this morning :)

Ha, no worries.  I've quite busy as well.  My girlfriend and I are caring for 4 kittens, and we already have 4 cats, 2 dogs and 5 hermit crabs.  It's a zoo here.  And she just got surgery on her ACL yesterday, so I'm basically doing everything right now.

> That is awesome! I must say, it was unexpected to see a message saying there had been a recent update to OpenPlay :)

Ha, I can imagine.  I'm glad to contribute.  And I'm glad to see you are still interested in it!

> Hint; don’t try to get fancy with git, keep it simple and it’s pretty decent. Bad things can happen if you start trying to use the advanced features without really understanding them. From experience ;p

Ha, sure, I'll be careful.  I like the GitHub Desktop app.  WAY better than MacCVS!

> No need, I’ve already forked it and made my first pull request. I can walk you through that if you’d like. This structure is how git wants to work, it can get messy if you don’t follow that (git basically wants all developers using their own repos, using a ’tree’ structure of pull requests). I have another pull request ready once the current is merged that addresses some fairly serious and not-so serious issues identified by the clang static code analysis.

That's cool that you are working on these issues.  Are you planning on doing a new PR to my repo?  I don't mind giving you direct access.  I could even transfer ownership of the repo to you.  I do love OpenPilot, but obviously you have way more investment in it than I do.  Whatever you'd like to do is fine with me.

> Very little, but I just happened to be unable to sleep last night, so good timing :)

Haha, yes, I don't normally stay up until 5 am either.

> I am doing a bunch of Apple II projects in my spare time. See http://www.ideasfromthedeep.com for two big ones. Professionally, I work on the Mac team at Quicken, inc. on their desktop personal finance application. It’s a great team and the product continues to get better.

Wow, that Apple II stuff looks pretty thorough.  No wonder you don't have any time!  Glad you like your team at Quicken.

> That would work. In that case, you can reject and close my pull request with that note. This is one of the good things about the git structure, you don’t have to revert my changes, just not accept them when you have a better solution.

Sure, makes sense.

> Heh, that’s great to hear. It’s amazing it’s still being used after all these years. I look forward to checking out Battle for the Universe once it runs on OS X 12+. Later,

Definitely worth maintaining OpenPlay, imo.  I will get Battle for the Universe there.  I just need to find these kittens a home first!

PS Let me know if you want to take ownership of the repo, or at least have direct access to mine.

**Comment by lroathe** [comment]
Direct access to your repo would be fine, I don't need ownership :)

I'll create the new pull request next.

**Comment by keithmalkin** [comment]
Sounds great 👍

**Pull request closed without merging**
